### PR TITLE
Update Indonesian Localizable

### PR DESCRIPTION
**Pull request by brynts**
Indonesian Language (Bahasa Indonesia)
contact: bryanthavok@me.com

### CODE REVIEW

**Comment by brynts** [comment]
hmm.. why? I'm edited manually in 2 hour..

**Comment by friggog** [comment]
Don't worry, I've included your translation - it needed to be in the folder id.lproj for Indonesian rather than in the English one. I've added it manually myself and closed the pull request instead of merging.
Your translation is here: https://github.com/friggog/Localisations/blob/master/seng/id.lproj/Localizable.strings
If you have any update in the future, simply edit this file in your fork and submit another pull request

**Comment by brynts** [comment]
haha okay, I don't really know about github.. thank you.. :D

**Comment by brynts** [comment]
haha okay, I don't really know about github.. thank you.. :D

**Pull request closed without merging**
